### ISSUE TITLE
Need to implement selectable list of past devices

### ISSUE THREAD

**Issue by timoreimann** [2cloud/android#16]
Users should be able to select from a list of devices they sent links to in the past.

My personal use case is that I frequently send links to either of two Chrome instances (work and home) which means that I keep overwriting/changing the target device field quite often. Implementing this feature would make alternation between the two devices a lot easier.

Also, it should be possible to remove items from the list again to account for wrongly filled or obsolete devices.

**Comment by paddycarver** [comment]
Agreed on all fronts. This is one of the things we plan to introduce in our next update.

**Comment by paddycarver** [comment]
Going to close this, as we've moved off Github. The issue will definitely be resolved, however.

(He says, 3 years later.)
